### ISSUE TITLE
Moving backup to trash when deleting

### ISSUE THREAD

**Issue by yiyin** [UziTech/sync-settings-folder-location#115]
1. It is not clear in the Installation instruction how the backup will be created under the specified back-up location. Will a new folder be created under the folder, or directly in the specified location?
 2. When removing the backup, can the files be moved to Trash instead of being directly deleted?

The combination of the above two led to the entire folder that I specified being deleted when doing sync-settings: delete-backup, not just the new folders created for the backup.

**Comment by UziTech** [comment]
When creating the backup the folder that you specify is created if it does not already exist. When deleting the folder that you specify is removed.

I can look into moving to trash instead. If you want to create a PR it will probably be done faster. 😁👍

**Comment by UziTech** [comment]
It looks like we would need to use something like [`trash`](https://www.npmjs.com/package/trash) for this but it seems it requires downloading binaries. I don't think we will be adding this feature. If you want to keep track of old settings even after updating them you can use [`sync-settings-git-location`](https://github.com/UziTech/sync-settings-git-location) to keep track of changes in a git repo.
