### ISSUE TITLE
About "Blacklisted Keys setting" in README

### ISSUE THREAD

**Issue by niss88** [UziTech/sync-settings-folder-location#190]
It says "Enter sync-settings-folder-location.folderPath into the Blacklisted Keys setting" in the "How to sync to different folder paths on different machines" section in README but "Blacklisted Keys setting" in Sync-Settings settings seems to have been changed to "Disallowed Settings"

versions sync-settings 5.2.15, sync-settings-folder-location 1.0.19

**Comment by UziTech** [comment]
fixed
