### ISSUE TITLE
Relative path to backup folder

### ISSUE THREAD

**Issue by aubreyz** [UziTech/sync-settings-folder-location#36]
This is a great package deserving wider use.  One issue I think is that the path to the backup folder is part of the backup. This is obviously not an issue with storing on git, but is an issue here when transferring settings between machines (unless the path to backup is identical). 

Might there be some way around this -- either not transferring the path to backup at all somehow under some circumstances, or using a relative path (relative to .atom). The latter might also not always be convenient if using say google drive or a NAS to transfer. 

Or best perhaps simply ignoring the path on restore and backup (if one already exists), or having a setting in the package itself to restore or not restore the path. Or maybe I am missing something altogether and it is already possible.

**Comment by UziTech** [comment]
There is a way to prevent certain settings from being included in the backup.

1. Go to the `Sync-Settings` settings
2. Enter `sync-settings-folder-location.folderPath` into the Blacklisted Keys setting
   ![image](https://user-images.githubusercontent.com/97994/86014931-94e6ed00-b9e6-11ea-855e-d7a02a3b157e.png)

**Comment by aubreyz** [comment]
Wow, I missed that... worthy for the Readme as it must be a common use-case for anyone synching between machines without git.

**Comment by UziTech** [comment]
If you want to create a PR for the readme I would be happy to review it. 😁

**Comment by aubreyz** [comment]
Will do - let me test it across my machines first.

**Comment by UziTech** [comment]
I also created a PR for sync-settings to test if it would be possible for other packages to list keys that shouldn't be backed up. https://github.com/atom-community/sync-settings/pull/517

**Comment by UziTech** [comment]
Or maybe sync-settings-folder-location could automatically add `sync-settings-folder-location.folderPath` to the sync-settings blacklist?
